/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.103
 * Generated at: 2024-11-12 00:19:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Date;
import java.util.Calendar;

public final class footer_jspf extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


/**
 This application is for demonstration use only. It contains known application security
vulnerabilities that were created expressly for demonstrating the functionality of
application security testing tools. These vulnerabilities may present risks to the
technical environment in which the application is installed. You must delete and
uninstall this demonstration application upon completion of the demonstration for
which it is intended. 

IBM DISCLAIMS ALL LIABILITY OF ANY KIND RESULTING FROM YOUR USE OF THE APPLICATION
OR YOUR FAILURE TO DELETE THE APPLICATION FROM YOUR ENVIRONMENT UPON COMPLETION OF
A DEMONSTRATION. IT IS YOUR RESPONSIBILITY TO DETERMINE IF THE PROGRAM IS APPROPRIATE
OR SAFE FOR YOUR TECHNICAL ENVIRONMENT. NEVER INSTALL THE APPLICATION IN A PRODUCTION
ENVIRONMENT. YOU ACKNOWLEDGE AND ACCEPT ALL RISKS ASSOCIATED WITH THE USE OF THE APPLICATION.

IBM AltoroJ
(c) Copyright IBM Corp. 2008, 2013 All Rights Reserved.
*/

      out.write(" \n");
      out.write("\n");
      out.write("<!-- BEGIN FOOTER -->\n");
      out.write("\n");
      out.write("\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<div id=\"footer\" style=\"width: 99%;\">\n");
      out.write("    <a id=\"HyperLink5\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp?content=privacy.htm\">Privacy Policy</a>\n");
      out.write("    &nbsp;&nbsp;|&nbsp;&nbsp;\n");
      out.write("    <a id=\"HyperLink6\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp?content=security.htm\">Security Statement</a>\n");
      out.write("    &nbsp;&nbsp;|&nbsp;&nbsp;\n");
      out.write("    <a id=\"HyperLink6\" href=\"");
      out.print(request.getContextPath());
      out.write("/status_check.jsp\">Server Status Check</a>\n");
      out.write("    &nbsp;&nbsp;|&nbsp;&nbsp; \n");
      out.write("    <a id=\"HyperLink6\" href=\"");
      out.print(request.getContextPath());
      out.write("/swagger/index.html\">REST API</a>\n");
      out.write("    &nbsp;&nbsp;|&nbsp;&nbsp; \n");
      out.write("    &copy;&nbsp;");
 out.print(Calendar.getInstance().get(Calendar.YEAR)); 
      out.write(" Altoro Mutual, Inc.\n");
      out.write("    <span style=\"color:red;font-weight:bold;font-style:italic;float:right\">This web application is open source!<span style=\"color:black;font-style:italic;font-weight:normal;float:right\">&nbsp;<a href=\"https://github.com/AppSecDev/AltoroJ/\">Get your copy from GitHub</a> and take advantage of advanced features</span></span>\n");
      out.write("\t<br><br><br>\n");
      out.write("    <div class=\"disclaimer\">\n");
      out.write("        The AltoroJ website is published by HCL Technologies, Ltd. for the sole purpose of\n");
      out.write("        demonstrating the effectiveness of HCL products in detecting web application\n");
      out.write("        vulnerabilities and website defects. This site is not a real banking site. Similarities,\n");
      out.write("        if any, to third party products and/or websites are purely coincidental. This site is\n");
      out.write("        provided \"as is\" without warranty of any kind, either express or implied. HCL does\n");
      out.write("        not assume any risk in relation to your use of this website. For more information,\n");
      out.write("        please go to <a id=\"HyperLink7\" href=\"https://www.hcl-software.com/appscan/\" >https://www.hcl-software.com/appscan/</a>.<br /><br />\n");
      out.write("\n");
      out.write("        Copyright &copy; 2008, 2017, IBM Corporation, All rights reserved.\n");
      out.write("        Copyright &copy; 2017, ");
 out.print(Calendar.getInstance().get(Calendar.YEAR)); 
      out.write(", HCL Technologies, Ltd., All rights reserved.\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<!-- END FOOTER -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
