/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.103
 * Generated at: 2024-11-12 00:19:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.ibm.security.appscan.altoromutual.util.ServletUtil;

public final class header_jspf extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

/**
 This application is for demonstration use only. It contains known application security
vulnerabilities that were created expressly for demonstrating the functionality of
application security testing tools. These vulnerabilities may present risks to the
technical environment in which the application is installed. You must delete and
uninstall this demonstration application upon completion of the demonstration for
which it is intended. 

IBM DISCLAIMS ALL LIABILITY OF ANY KIND RESULTING FROM YOUR USE OF THE APPLICATION
OR YOUR FAILURE TO DELETE THE APPLICATION FROM YOUR ENVIRONMENT UPON COMPLETION OF
A DEMONSTRATION. IT IS YOUR RESPONSIBILITY TO DETERMINE IF THE PROGRAM IS APPROPRIATE
OR SAFE FOR YOUR TECHNICAL ENVIRONMENT. NEVER INSTALL THE APPLICATION IN A PRODUCTION
ENVIRONMENT. YOU ACKNOWLEDGE AND ACCEPT ALL RISKS ASSOCIATED WITH THE USE OF THE APPLICATION.

IBM AltoroJ
(c) Copyright IBM Corp. 2008, 2013 All Rights Reserved.
*/

      out.write(" \n");
      out.write("\n");
      out.write("<!-- BEGIN HEADER -->\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n");
      out.write("\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" >\n");
      out.write("\n");
 boolean loggedIn = request.getSession().getAttribute("user") != null; 
      out.write("\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\t<title>Altoro Mutual</title>\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\" />\n");
      out.write("  <link href=\"");
      out.print(request.getContextPath());
      out.write("/style.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("</head>\n");
      out.write("<body style=\"margin-top:5px;\">\n");
      out.write("\n");
      out.write("<div id=\"header\" style=\"margin-bottom:5px; width: 99%;\">\n");
      out.write("  <form id=\"frmSearch\" method=\"get\" action=\"");
      out.print(request.getContextPath());
      out.write("/search.jsp\">\n");
      out.write("\t  <table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("\t\t  <tr>\n");
      out.write("\t\t      <td rowspan=\"2\"><a id=\"HyperLink1\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/logo.gif\" width=283 height=80/></a></td>\n");
      out.write("\t\t\t  <td align=\"right\" valign=\"top\">\n");
      out.write("  \t\t\t  <a id=\"LoginLink\" href=\"");
      out.print((!loggedIn)?request.getContextPath()+"/login.jsp":request.getContextPath()+"/logout.jsp");
      out.write("\"><font style=\"font-weight: bold; color: red;\">");
      out.print((!loggedIn)?"Sign In":"Sign Off");
      out.write("</font></a> | <a id=\"HyperLink3\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp?content=inside_contact.htm\">Contact Us</a> | <a id=\"HyperLink4\" href=\"");
      out.print(request.getContextPath());
      out.write("/feedback.jsp\">Feedback</a> | <label for=\"txtSearch\">Search</label>\n");
      out.write("          <input type=\"text\" name=\"query\" id=\"query\" accesskey=\"S\" />\n");
      out.write("          <input type=\"submit\" value=\"Go\" />\n");
      out.write("\t\t\t  </td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t\t  <tr>\n");
      out.write("\t\t\t  <td align=\"right\" style=\"background-image:url('");
      out.print(request.getContextPath());
      out.write("/images/gradient.jpg');padding:0px;margin:0px;\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/images/header_pic.jpg\" alt=\"\" width=354 height=60/></td>\n");
      out.write("\t\t  </tr>\n");
      out.write("\t  </table>\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<table cellspacing=\"0\" width=\"100%\">\n");
      out.write("  <tr>\n");
      out.write("    <td width=\"25%\" class=\"bt br bb\"><div id=\"Header1\"><img id=\"Image1\" src=\"");
      out.print(request.getContextPath());
      out.write("/images/pf_lock.gif\" width=12 height=14 style=\"vertical-align: bottom;\" alt=\"Secure Login\"/> &nbsp; <a id=\"AccountLink\" href=\"");
      out.print((loggedIn)?request.getContextPath()+"/bank/main.jsp":request.getContextPath()+"/login.jsp");
      out.write("\" class=\"focus\" >");
      out.print((loggedIn)?"MY ACCOUNT":"ONLINE BANKING LOGIN");
      out.write("</a></div></td>\n");
      out.write("    <td width=\"25%\" class=\"cc bt br bb\"><div id=\"Header2\"><a id=\"LinkHeader2\" class=\"focus\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp?content=personal.htm\" >PERSONAL</a></div></td>\n");
      out.write("    <td width=\"25%\" class=\"cc bt br bb\"><div id=\"Header3\"><a id=\"LinkHeader3\" class=\"focus\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp?content=business.htm\" >SMALL BUSINESS</a></div></td>\n");
      out.write("    <td width=\"25%\" class=\"cc bt bb\"><div id=\"Header4\"><a id=\"LinkHeader4\" class=\"focus\" href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp?content=inside.htm\">INSIDE ALTORO MUTUAL</a></div></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("  \n");
      out.write("  <!-- END HEADER -->\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
